//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameWebDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Msgs = new HashSet<Msg>();
        }
    
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public string AccountPwd { get; set; }
        public Nullable<int> AccountSex { get; set; }
        public string AccountEmail { get; set; }
    
        public virtual ICollection<Msg> Msgs { get; set; }
    }
}
