//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameWebDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
<<<<<<< HEAD
    public partial class GameDBEntities1 : DbContext
    {
        public GameDBEntities1()
            : base("name=GameDBEntities1")
=======
    public partial class GameDBEntities : DbContext
    {
        public GameDBEntities()
            : base("name=GameDBEntities")
>>>>>>> 4aea17a9135a33304ff4e47dd424853f0526a140
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Msg> Msgs { get; set; }
    }
}
